/* Hazır 6 slaytlık şablonlar. Yapı, AI içe aktarma formatıyla birebir aynı:
   template = tüm slaytlara uygulanan stil, slides = slayt bazlı metin + istisnalar.
   Metinler {tr,en} olarak tutulur; arayüz dili hangisiyse o kullanılır. */
(function (global) {
  const S = (tr, en, extra) => Object.assign({ title: tr[0], subtitle: tr[1] }, extra, {
    title: { tr: tr[0], en: en[0] },
    subtitle: { tr: tr[1], en: en[1] },
  });

  global.TEMPLATES = [
    {
      key: 'court',
      name: { tr: 'Kort', en: 'Court' },
      cat: { tr: 'Spor · skor · telefon + saat', en: 'Sport · score · phone + watch' },
      template: {
        font: 'georgia', frame: 'iphone-pro', deviceColor: 'graphite', layout: 'text-top',
        background: { type: 'mesh', c1: '#9a3412', c2: '#7f1d1d', c3: '#1c1917', pattern: 'none', noise: 12, vignette: 34 },
        titleSize: 5.8, subSize: 2.9, weight: 700, letterSpacing: 0,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 78, textY: 5,
        deviceSize: 56, deviceY: 33, deviceRot: 0, fit: 'top',
        device2: { on: true, frame: 'watch', color: 'silver', w: 23, x: 21, y: 30, rot: 8, front: true, fit: 'cover', shadow: 55 },
      },
      slides: [
        S(['Her maçı kaydet', 'Tenis ve padel geçmişin cebinde'], ['Track every match', 'Your tennis and padel history, on you']),
        S(['Skoru bileğinden tut', 'Saatinden tek dokunuşla puan ekle'], ['Score from your wrist', 'One tap per point, straight from the watch']),
        S(['Kendi kurallarını kur', 'Set, tie-break ve deuce ayarları sende'], ['Set your own rules', 'Sets, tie-breaks and deuce, your way']),
        S(['Rakibinle eşleş', 'QR ile skor iki telefonda aynı anda'], ['Sync with your rival', 'One QR and the score lives on both phones']),
        S(['Zaferini paylaş', 'Maç kartını saniyeler içinde gönder'], ['Share the win', 'A match card ready to post in seconds']),
        S(['Gelişimini gör', 'Kazanma oranın ve istatistiklerin tek ekranda'], ['See your progress', 'Win rate and stats on one screen']),
      ],
    },
    {
      key: 'lingo',
      name: { tr: 'Lingo', en: 'Lingo' },
      cat: { tr: 'Eğitim · mor gradyan', en: 'Learning · violet gradient' },
      template: {
        font: 'system', frame: 'iphone-pro', deviceColor: 'black', layout: 'text-top',
        background: { type: 'linear', c1: '#7c3aed', c2: '#a78bfa', angle: 160, pattern: 'none', noise: 0, vignette: 0 },
        titleSize: 6.6, subSize: 3.2, weight: 800, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 85, textY: 6,
        deviceSize: 70, deviceY: 31, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Dakikalar içinde\nöğren', 'Günde 5 dakika yeterli'], ['Learn a language\nin minutes', 'Five minutes a day is enough']),
        S(['Konuşarak ilerle', 'Telaffuzun anında puanlanır'], ['Speak with confidence', 'Your pronunciation, scored instantly']),
        S(['Serini kaybetme', 'Küçük hedefler, her gün devam'], ['Keep your streak', 'Small goals, every single day']),
        S(['40 dil, tek uygulama', 'İstediğin dile istediğin an geç'], ['40 languages, one app', 'Switch whenever you feel like it']),
        S(['Cebinde ders yok', 'Metroda, kuyrukta, molada çalış'], ['No desk required', 'On the train, in a queue, on a break']),
        S(['Bugün başla', 'İlk ders ücretsiz'], ['Start today', 'The first lesson is free']),
      ],
    },
    {
      key: 'pluto',
      name: { tr: 'Pluto', en: 'Pluto' },
      cat: { tr: 'Finans · açık, temiz', en: 'Finance · light and clean' },
      template: {
        font: 'avenir', frame: 'iphone-pro', deviceColor: 'black', layout: 'bleed',
        background: { type: 'solid', c1: '#f3f4f6', pattern: 'none', noise: 0, vignette: 0 },
        titleSize: 6.4, subSize: 3.1, weight: 700, letterSpacing: -1,
        textColor: '#111214', subColor: '#111214', subOpacity: 62, textY: 6,
        deviceSize: 78, deviceY: 34, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Paran nerede,\ngör', 'Tüm hesapların tek ekranda'], ['Watch your accounts\ngrow', 'Every account on one screen'], { background: { type: 'solid', c1: '#dbeafe' } }),
        S(['Harcamanı çöz', 'Kategoriler kendiliğinden ayrılır'], ['Visualise your spending', 'Categories sort themselves out']),
        S(['Bütçen kontrolde', 'Ay sonunu önceden gör'], ['Budget without effort', 'See the end of the month in advance'], { background: { type: 'solid', c1: '#dbeafe' } }),
        S(['Sesle kaydet', 'Fişi say, gerisini uygulama yazsın'], ['Log it by voice', 'Say the receipt, the app writes it down']),
        S(['Aboneliklerini yakala', 'Unuttuğun ödemeler artık görünür'], ['Catch subscriptions', 'The payments you forgot are now visible'], { background: { type: 'solid', c1: '#dbeafe' } }),
        S(['Hedefine yaklaş', 'Birikimini adım adım büyüt'], ['Reach your goal', 'Grow your savings step by step']),
      ],
    },
    {
      key: 'astra',
      name: { tr: 'Astra', en: 'Astra' },
      cat: { tr: 'Sosyal · koyu lacivert · çift telefon', en: 'Social · deep navy · two phones' },
      template: {
        font: 'system', frame: 'iphone-pro', deviceColor: 'graphite', layout: 'text-top',
        background: { type: 'mesh', c1: '#4338ca', c2: '#7c3aed', c3: '#0b1020', pattern: 'none', noise: 6, vignette: 26 },
        titleSize: 6.2, subSize: 3.1, weight: 700, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 80, textY: 6,
        deviceSize: 58, deviceX: 10, deviceY: 34, deviceRot: 5, fit: 'top',
        device2: { on: true, frame: 'iphone-pro', color: 'silver', w: 48, x: -24, y: 40, rot: -7, front: false, fit: 'top', shadow: 40 },
      },
      slides: [
        S(['Ekibinle tek yerde', 'Gruplar, sohbetler, hepsi düzenli'], ['Groups with your mates', 'Chats and threads, finally tidy']),
        S(['Hiçbir mesajı kaçırma', 'Önemli olan hep en üstte'], ['Never miss a message', 'What matters stays on top']),
        S(['Anı paylaş', 'Fotoğraf ve not aynı akışta'], ['Share the moment', 'Photos and notes in one flow']),
        S(['Sessiz saatler', 'Rahatsız edilmeden konuş'], ['Quiet hours', 'Talk without being interrupted']),
        S(['Uçtan uca güvenli', 'Konuşman sadece sizde kalır'], ['End-to-end private', 'Your conversation stays yours']),
        S(['Arkadaşlarını çağır', 'Bir linkle herkes içeride'], ['Bring your people', 'One link and everyone is in']),
      ],
    },
    {
      key: 'mono',
      name: { tr: 'Mono', en: 'Mono' },
      cat: { tr: 'Minimal · siyah beyaz · çerçevesiz', en: 'Minimal · black & white · frameless' },
      template: {
        font: 'helvetica-neue', frame: 'none', deviceColor: 'black', layout: 'text-top',
        background: { type: 'solid', c1: '#0b0b0d', pattern: 'none', noise: 8, vignette: 20 },
        titleSize: 7.4, subSize: 3.1, weight: 800, letterSpacing: -2,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 60, textY: 7,
        deviceSize: 82, deviceY: 30, deviceRot: 0, fit: 'top', deviceShadow: 60,
      },
      slides: [
        S(['Tek bir şey.\nİyi yap.', 'Dikkatini dağıtan hiçbir şey yok'], ['One thing.\nDone well.', 'Nothing here fights for your attention']),
        S(['Alışkanlığını kur', 'Günde bir dokunuş yeter'], ['Build the habit', 'One tap a day is the whole ritual']),
        S(['Seriyi büyüt', 'İlerlemeni sade bir çizgide gör'], ['Grow the streak', 'Progress on one clean line']),
        S(['Hatırlatma, gıcık değil', 'Doğru anda tek bildirim'], ['Reminders, not nagging', 'One notification, at the right time']),
        S(['Veri sende kalır', 'Hesap yok, takip yok'], ['Your data stays put', 'No account, no tracking']),
        S(['Bugün başla', 'Kurulum otuz saniye'], ['Start today', 'Setup takes thirty seconds']),
      ],
    },
    {
      key: 'editorial',
      name: { tr: 'Editöryel', en: 'Editorial' },
      cat: { tr: 'Günlük · krem · serif', en: 'Journal · cream · serif' },
      template: {
        font: 'georgia', frame: 'iphone-notch', deviceColor: 'silver', layout: 'small',
        background: { type: 'linear', c1: '#fdfcfb', c2: '#e2d1c3', angle: 150, pattern: 'none', noise: 6, vignette: 12 },
        titleSize: 5.6, subSize: 2.9, weight: 600, letterSpacing: 1,
        textColor: '#1c1917', subColor: '#1c1917', subOpacity: 62, textY: 7,
        deviceSize: 54, deviceY: 38, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Günün nasıl geçti?', 'Bir sayfa yazmak yeterli'], ['How was your day?', 'One page is enough']),
        S(['Hatırlamak için yaz', 'Anılarını tarihiyle sakla'], ['Write to remember', 'Keep your memories with their dates']),
        S(['Ruh halini takip et', 'Haftalık örüntünü gör'], ['Track your mood', 'See the pattern of your week']),
        S(['Fotoğrafını ekle', 'Yazıyla birlikte o an da kalsın'], ['Add the photograph', 'Keep the moment next to the words']),
        S(['Sadece sana ait', 'Şifreli, cihazında, kapalı kapılar ardında'], ['Yours alone', 'Encrypted, on device, behind closed doors']),
        S(['Bu akşam başla', 'İlk sayfa seni bekliyor'], ['Start tonight', 'The first page is waiting']),
      ],
    },
    {
      key: 'neon',
      name: { tr: 'Neon', en: 'Neon' },
      cat: { tr: 'Müzik · koyu · halka desen', en: 'Music · dark · ring pattern' },
      template: {
        font: 'futura', frame: 'iphone-pro', deviceColor: 'black', layout: 'tilt',
        background: { type: 'mesh', c1: '#7c3aed', c2: '#06b6d4', c3: '#07070c', pattern: 'rings', patternColor: '#ffffff', patternOpacity: 9, noise: 10, vignette: 30 },
        titleSize: 6.4, subSize: 3.0, weight: 700, letterSpacing: 3,
        textColor: '#ffffff', subColor: '#a5f3fc', subOpacity: 90, textY: 6,
        deviceSize: 62, deviceY: 32, deviceRot: -8, fit: 'top',
      },
      slides: [
        S(['Sesini yükselt', 'Kütüphanen, senin ritminde'], ['Turn it up', 'Your library, your rhythm']),
        S(['Çalma listeni kur', 'Sürükle, bırak, çal'], ['Build the playlist', 'Drag, drop, play']),
        S(['Çevrimdışı dinle', 'İnternet yoksa da müzik var'], ['Listen offline', 'No signal, still sound']),
        S(['Sözleri yakala', 'Şarkı ilerledikçe akan sözler'], ['Catch the lyrics', 'Words that follow the track']),
        S(['Keşfet', 'Sevdiğin sesin komşuları'], ['Discover', 'Neighbours of the sound you love']),
        S(['Sese dal', 'İlk ay ücretsiz'], ['Dive in', 'First month on us']),
      ],
    },
    {
      key: 'sunset',
      name: { tr: 'Gün batımı', en: 'Sunset' },
      cat: { tr: 'Fitness · turuncu · dönüşümlü eğim', en: 'Fitness · orange · alternating tilt' },
      template: {
        font: 'avenir', frame: 'android', deviceColor: 'black', layout: 'right',
        background: { type: 'linear', c1: '#f97316', c2: '#ef4444', angle: 145, pattern: 'diagonal', patternColor: '#ffffff', patternOpacity: 7, noise: 6, vignette: 18 },
        titleSize: 6.2, subSize: 3.1, weight: 800, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 85, textY: 8,
        deviceSize: 60, deviceY: 34, fit: 'top',
      },
      slides: [
        S(['Antrenmanını\nkaydet', 'Her set, her tekrar yerinde'], ['Log every\nworkout', 'Every set, every rep, kept']),
        S(['Programını kur', 'Haftanı önceden planla'], ['Plan your split', 'Set the week in advance'], { layout: 'left' }),
        S(['Ağırlığını artır', 'Bir sonraki hedefi uygulama söyler'], ['Add the weight', 'The app tells you the next target']),
        S(['Molanı ölç', 'Zamanlayıcı sette kendini başlatır'], ['Time your rest', 'The timer starts itself'], { layout: 'left' }),
        S(['Formunu gör', 'Hacim ve güç eğrisi tek grafikte'], ['See your shape', 'Volume and strength in one chart']),
        S(['İlk antrenman bugün', 'Ücretsiz başla'], ['First session today', 'Start for free'], { layout: 'small' }),
      ],
    },
    {
      key: 'duo',
      name: { tr: 'İkili', en: 'Duo' },
      cat: { tr: 'Fotoğraf · iki telefon · buz mesh', en: 'Photo · two phones · ice mesh' },
      template: {
        font: 'system', frame: 'iphone-pro', deviceColor: 'white', layout: 'text-top',
        background: { type: 'mesh', c1: '#38bdf8', c2: '#a78bfa', c3: '#0b1220', pattern: 'none', noise: 8, vignette: 24 },
        titleSize: 6.0, subSize: 3.0, weight: 700, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 82, textY: 6,
        deviceSize: 52, deviceX: -14, deviceY: 36, deviceRot: -6, fit: 'top',
        device2: { on: true, frame: 'iphone-pro', color: 'graphite', w: 52, x: 18, y: 30, rot: 7, front: true, fit: 'top', shadow: 50 },
      },
      slides: [
        S(['Öncesi ve sonrası', 'Tek dokunuşta fark ortaya çıksın'], ['Before and after', 'One tap and the difference shows']),
        S(['Filmi geri getir', 'Analog tonlar, dijital kolaylık'], ['Bring the film back', 'Analogue tones, digital ease']),
        S(['Renkleri sen kur', 'Eğriler, tonlar, grenler sende'], ['Own the colour', 'Curves, tones and grain are yours']),
        S(['Ayarını sakla', 'Kendi ön ayarını bir kez kur'], ['Save the look', 'Build your preset once']),
        S(['Toplu düzenle', 'Bütün seriye aynı ton'], ['Edit in batches', 'One look across the whole set']),
        S(['Paylaşmaya hazır', 'Kalite kaybı olmadan dışa aktar'], ['Ready to post', 'Export without losing quality']),
      ],
    },
    {
      key: 'grid',
      name: { tr: 'Izgara', en: 'Grid' },
      cat: { tr: 'Verimlilik · açık gri · ızgara desen', en: 'Productivity · light grey · grid' },
      template: {
        font: 'helvetica-neue', frame: 'iphone-pro', deviceColor: 'silver', layout: 'text-top',
        background: { type: 'solid', c1: '#eef0f4', pattern: 'grid', patternColor: '#0b0b0d', patternOpacity: 7, noise: 0, vignette: 10 },
        titleSize: 5.8, subSize: 2.9, weight: 700, letterSpacing: -1,
        textColor: '#111214', subColor: '#111214', subOpacity: 60, textY: 6,
        deviceSize: 62, deviceY: 30, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Bugünü topla', 'Yapılacaklar tek listede'], ['Gather your day', 'Every task in one list']),
        S(['Önceliği belirle', 'Önemli olan üstte kalsın'], ['Set the priority', 'What matters stays on top']),
        S(['Projelere böl', 'İş ve özel hayat ayrı kalsın'], ['Split into projects', 'Work and life, kept apart']),
        S(['Takvimle eşleş', 'Görevler günün içine otursun'], ['Meet your calendar', 'Tasks land inside the day']),
        S(['Tekrarı otomatikleştir', 'Her hafta yeniden yazma'], ['Automate the routine', 'Stop rewriting the same week']),
        S(['Zihnin boşalsın', 'Bugün düzeni kur'], ['Clear your head', 'Set it up today']),
      ],
    },
    {
      key: 'ocean',
      name: { tr: 'Okyanus', en: 'Ocean' },
      cat: { tr: 'Sağlık · metin altta · geniş harf aralığı', en: 'Wellness · text below · wide tracking' },
      template: {
        font: 'futura', frame: 'iphone-pro', deviceColor: 'silver', layout: 'text-bottom',
        background: { type: 'linear', c1: '#0ea5e9', c2: '#0f766e', angle: 165, pattern: 'none', noise: 6, vignette: 22 },
        titleSize: 5.4, subSize: 2.8, weight: 600, letterSpacing: 6,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 80, textY: 76,
        deviceSize: 58, deviceY: 6, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Nefesini yavaşlat', 'Üç dakikalık kısa seanslar'], ['Slow your breath', 'Short three-minute sessions']),
        S(['Günü sakin aç', 'Sabah ritüelin hazır'], ['Open the day calmly', 'Your morning ritual is ready']),
        S(['Uykunu izle', 'Gece boyunca ne olduğunu gör'], ['Watch your sleep', 'See what the night looked like']),
        S(['Suyunu unutma', 'Nazik hatırlatmalar'], ['Remember to drink', 'Gentle nudges, nothing loud']),
        S(['Haftanı oku', 'Ruh hâli ve enerji birlikte'], ['Read your week', 'Mood and energy side by side']),
        S(['Bugün başla', 'İlk hafta ücretsiz'], ['Begin today', 'The first week is free']),
      ],
    },
    {
      key: 'night',
      name: { tr: 'Gece', en: 'Night' },
      cat: { tr: 'Gece · derin siyah · sakin', en: 'Night · deep black · quiet' },
      template: {
        font: 'georgia', frame: 'iphone-pro', deviceColor: 'black', layout: 'text-top',
        background: { type: 'radial', c1: '#1e293b', c2: '#04040a', pattern: 'dots', patternColor: '#ffffff', patternOpacity: 8, noise: 10, vignette: 45 },
        titleSize: 5.6, subSize: 2.9, weight: 600, letterSpacing: 1,
        textColor: '#e2e8f0', subColor: '#94a3b8', subOpacity: 95, textY: 6,
        deviceSize: 60, deviceY: 32, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Gece moduna geç', 'Gözünü yormayan bir arayüz'], ['Switch to night', 'An interface that spares your eyes']),
        S(['Uykuya hazırlan', 'Ekran ısınır, zihin yavaşlar'], ['Wind down', 'The screen warms, the mind slows']),
        S(['Sesleri seç', 'Yağmur, uğultu, sessizlik'], ['Choose the sound', 'Rain, hum or silence']),
        S(['Alarmın nazik olsun', 'Hafif uykuda uyandırır'], ['A kinder alarm', 'Wakes you in light sleep']),
        S(['Sabahı gör', 'Gecenin özeti kahvenle gelsin'], ['See the morning', 'Your night, summarised with coffee']),
        S(['Bu gece dene', 'Kurulum bir dakikadan kısa'], ['Try it tonight', 'Setup takes under a minute']),
      ],
    },
  ];
})(window);
