/* Hazır 6 slaytlık şablonlar. Yapı, AI içe aktarma formatıyla birebir aynı:
   template = tüm slaytlara uygulanan stil, slides = slayt bazlı metin + istisnalar.
   Metinler {tr,en} olarak tutulur; arayüz dili hangisiyse o kullanılır. */
(function (global) {
  const S = (tr, en, extra) => Object.assign({ title: tr[0], subtitle: tr[1] }, extra, {
    title: { tr: tr[0], en: en[0] },
    subtitle: { tr: tr[1], en: en[1] },
  });

  global.TEMPLATES = [
    {
      key: 'court',
      tags: ['spor', 'koyu'],
      name: { tr: 'Kort', en: 'Court' },
      cat: { tr: 'Spor · skor · telefon + saat', en: 'Sport · score · phone + watch' },
      template: {
        font: 'georgia', frame: 'iphone-pro', deviceColor: 'graphite', layout: 'text-top',
        background: { type: 'mesh', c1: '#9a3412', c2: '#7f1d1d', c3: '#1c1917', pattern: 'none', noise: 12, vignette: 34 },
        titleSize: 5.8, subSize: 2.9, weight: 700, letterSpacing: 0,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 78, textY: 5,
        deviceSize: 56, deviceY: 33, deviceRot: 0, fit: 'top',
        device2: { on: true, frame: 'watch', color: 'silver', w: 23, x: 21, y: 30, rot: 8, front: true, fit: 'cover', shadow: 55 },
      },
      slides: [
        S(['Her maçı kaydet', 'Tenis ve padel geçmişin cebinde'], ['Track every match', 'Your tennis and padel history, on you']),
        S(['Skoru bileğinden tut', 'Saatinden tek dokunuşla puan ekle'], ['Score from your wrist', 'One tap per point, straight from the watch']),
        S(['Kendi kurallarını kur', 'Set, tie-break ve deuce ayarları sende'], ['Set your own rules', 'Sets, tie-breaks and deuce, your way']),
        S(['Rakibinle eşleş', 'QR ile skor iki telefonda aynı anda'], ['Sync with your rival', 'One QR and the score lives on both phones']),
        S(['Zaferini paylaş', 'Maç kartını saniyeler içinde gönder'], ['Share the win', 'A match card ready to post in seconds']),
        S(['Gelişimini gör', 'Kazanma oranın ve istatistiklerin tek ekranda'], ['See your progress', 'Win rate and stats on one screen']),
      ],
    },
    {
      key: 'lingo',
      tags: ['egitim', 'renkli'],
      name: { tr: 'Lingo', en: 'Lingo' },
      cat: { tr: 'Eğitim · mor gradyan', en: 'Learning · violet gradient' },
      template: {
        font: 'system', frame: 'iphone-pro', deviceColor: 'black', layout: 'text-top',
        background: { type: 'linear', c1: '#7c3aed', c2: '#a78bfa', angle: 160, pattern: 'none', noise: 0, vignette: 0 },
        titleSize: 6.6, subSize: 3.2, weight: 800, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 85, textY: 6,
        deviceSize: 70, deviceY: 31, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Dakikalar içinde\nöğren', 'Günde 5 dakika yeterli'], ['Learn a language\nin minutes', 'Five minutes a day is enough']),
        S(['Konuşarak ilerle', 'Telaffuzun anında puanlanır'], ['Speak with confidence', 'Your pronunciation, scored instantly']),
        S(['Serini kaybetme', 'Küçük hedefler, her gün devam'], ['Keep your streak', 'Small goals, every single day']),
        S(['40 dil, tek uygulama', 'İstediğin dile istediğin an geç'], ['40 languages, one app', 'Switch whenever you feel like it']),
        S(['Cebinde ders yok', 'Metroda, kuyrukta, molada çalış'], ['No desk required', 'On the train, in a queue, on a break']),
        S(['Bugün başla', 'İlk ders ücretsiz'], ['Start today', 'The first lesson is free']),
      ],
    },
    {
      key: 'pluto',
      tags: ['finans', 'acik'],
      name: { tr: 'Pluto', en: 'Pluto' },
      cat: { tr: 'Finans · açık, temiz', en: 'Finance · light and clean' },
      template: {
        font: 'avenir', frame: 'iphone-pro', deviceColor: 'black', layout: 'bleed',
        background: { type: 'solid', c1: '#f3f4f6', pattern: 'none', noise: 0, vignette: 0 },
        titleSize: 6.4, subSize: 3.1, weight: 700, letterSpacing: -1,
        textColor: '#111214', subColor: '#111214', subOpacity: 62, textY: 6,
        deviceSize: 78, deviceY: 34, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Paran nerede,\ngör', 'Tüm hesapların tek ekranda'], ['Watch your accounts\ngrow', 'Every account on one screen'], { background: { type: 'solid', c1: '#dbeafe' } }),
        S(['Harcamanı çöz', 'Kategoriler kendiliğinden ayrılır'], ['Visualise your spending', 'Categories sort themselves out']),
        S(['Bütçen kontrolde', 'Ay sonunu önceden gör'], ['Budget without effort', 'See the end of the month in advance'], { background: { type: 'solid', c1: '#dbeafe' } }),
        S(['Sesle kaydet', 'Fişi say, gerisini uygulama yazsın'], ['Log it by voice', 'Say the receipt, the app writes it down']),
        S(['Aboneliklerini yakala', 'Unuttuğun ödemeler artık görünür'], ['Catch subscriptions', 'The payments you forgot are now visible'], { background: { type: 'solid', c1: '#dbeafe' } }),
        S(['Hedefine yaklaş', 'Birikimini adım adım büyüt'], ['Reach your goal', 'Grow your savings step by step']),
      ],
    },
    {
      key: 'astra',
      tags: ['sosyal', 'koyu'],
      name: { tr: 'Astra', en: 'Astra' },
      cat: { tr: 'Sosyal · koyu lacivert · çift telefon', en: 'Social · deep navy · two phones' },
      template: {
        font: 'system', frame: 'iphone-pro', deviceColor: 'graphite', layout: 'text-top',
        background: { type: 'mesh', c1: '#4338ca', c2: '#7c3aed', c3: '#0b1020', pattern: 'none', noise: 6, vignette: 26 },
        titleSize: 6.2, subSize: 3.1, weight: 700, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 80, textY: 6,
        deviceSize: 58, deviceX: 10, deviceY: 34, deviceRot: 5, fit: 'top',
        device2: { on: true, frame: 'iphone-pro', color: 'silver', w: 48, x: -24, y: 40, rot: -7, front: false, fit: 'top', shadow: 40 },
      },
      slides: [
        S(['Ekibinle tek yerde', 'Gruplar, sohbetler, hepsi düzenli'], ['Groups with your mates', 'Chats and threads, finally tidy']),
        S(['Hiçbir mesajı kaçırma', 'Önemli olan hep en üstte'], ['Never miss a message', 'What matters stays on top']),
        S(['Anı paylaş', 'Fotoğraf ve not aynı akışta'], ['Share the moment', 'Photos and notes in one flow']),
        S(['Sessiz saatler', 'Rahatsız edilmeden konuş'], ['Quiet hours', 'Talk without being interrupted']),
        S(['Uçtan uca güvenli', 'Konuşman sadece sizde kalır'], ['End-to-end private', 'Your conversation stays yours']),
        S(['Arkadaşlarını çağır', 'Bir linkle herkes içeride'], ['Bring your people', 'One link and everyone is in']),
      ],
    },
    {
      key: 'mono',
      tags: ['verimlilik', 'koyu'],
      name: { tr: 'Mono', en: 'Mono' },
      cat: { tr: 'Minimal · siyah beyaz · çerçevesiz', en: 'Minimal · black & white · frameless' },
      template: {
        font: 'helvetica-neue', frame: 'none', deviceColor: 'black', layout: 'text-top',
        background: { type: 'solid', c1: '#0b0b0d', pattern: 'none', noise: 8, vignette: 20 },
        titleSize: 7.4, subSize: 3.1, weight: 800, letterSpacing: -2,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 60, textY: 7,
        deviceSize: 82, deviceY: 30, deviceRot: 0, fit: 'top', deviceShadow: 60,
      },
      slides: [
        S(['Tek bir şey.\nİyi yap.', 'Dikkatini dağıtan hiçbir şey yok'], ['One thing.\nDone well.', 'Nothing here fights for your attention']),
        S(['Alışkanlığını kur', 'Günde bir dokunuş yeter'], ['Build the habit', 'One tap a day is the whole ritual']),
        S(['Seriyi büyüt', 'İlerlemeni sade bir çizgide gör'], ['Grow the streak', 'Progress on one clean line']),
        S(['Hatırlatma, gıcık değil', 'Doğru anda tek bildirim'], ['Reminders, not nagging', 'One notification, at the right time']),
        S(['Veri sende kalır', 'Hesap yok, takip yok'], ['Your data stays put', 'No account, no tracking']),
        S(['Bugün başla', 'Kurulum otuz saniye'], ['Start today', 'Setup takes thirty seconds']),
      ],
    },
    {
      key: 'editorial',
      tags: ['gunluk', 'acik'],
      name: { tr: 'Editöryel', en: 'Editorial' },
      cat: { tr: 'Günlük · krem · serif', en: 'Journal · cream · serif' },
      template: {
        font: 'georgia', frame: 'iphone-notch', deviceColor: 'silver', layout: 'small',
        background: { type: 'linear', c1: '#fdfcfb', c2: '#e2d1c3', angle: 150, pattern: 'none', noise: 6, vignette: 12 },
        titleSize: 5.6, subSize: 2.9, weight: 600, letterSpacing: 1,
        textColor: '#1c1917', subColor: '#1c1917', subOpacity: 62, textY: 7,
        deviceSize: 54, deviceY: 38, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Günün nasıl geçti?', 'Bir sayfa yazmak yeterli'], ['How was your day?', 'One page is enough']),
        S(['Hatırlamak için yaz', 'Anılarını tarihiyle sakla'], ['Write to remember', 'Keep your memories with their dates']),
        S(['Ruh halini takip et', 'Haftalık örüntünü gör'], ['Track your mood', 'See the pattern of your week']),
        S(['Fotoğrafını ekle', 'Yazıyla birlikte o an da kalsın'], ['Add the photograph', 'Keep the moment next to the words']),
        S(['Sadece sana ait', 'Şifreli, cihazında, kapalı kapılar ardında'], ['Yours alone', 'Encrypted, on device, behind closed doors']),
        S(['Bu akşam başla', 'İlk sayfa seni bekliyor'], ['Start tonight', 'The first page is waiting']),
      ],
    },
    {
      key: 'neon',
      tags: ['muzik', 'koyu'],
      name: { tr: 'Neon', en: 'Neon' },
      cat: { tr: 'Müzik · koyu · halka desen', en: 'Music · dark · ring pattern' },
      template: {
        font: 'futura', frame: 'iphone-pro', deviceColor: 'black', layout: 'tilt',
        background: { type: 'mesh', c1: '#7c3aed', c2: '#06b6d4', c3: '#07070c', pattern: 'rings', patternColor: '#ffffff', patternOpacity: 9, noise: 10, vignette: 30 },
        titleSize: 6.4, subSize: 3.0, weight: 700, letterSpacing: 3,
        textColor: '#ffffff', subColor: '#a5f3fc', subOpacity: 90, textY: 6,
        deviceSize: 62, deviceY: 32, deviceRot: -8, fit: 'top',
      },
      slides: [
        S(['Sesini yükselt', 'Kütüphanen, senin ritminde'], ['Turn it up', 'Your library, your rhythm']),
        S(['Çalma listeni kur', 'Sürükle, bırak, çal'], ['Build the playlist', 'Drag, drop, play']),
        S(['Çevrimdışı dinle', 'İnternet yoksa da müzik var'], ['Listen offline', 'No signal, still sound']),
        S(['Sözleri yakala', 'Şarkı ilerledikçe akan sözler'], ['Catch the lyrics', 'Words that follow the track']),
        S(['Keşfet', 'Sevdiğin sesin komşuları'], ['Discover', 'Neighbours of the sound you love']),
        S(['Sese dal', 'İlk ay ücretsiz'], ['Dive in', 'First month on us']),
      ],
    },
    {
      key: 'sunset',
      tags: ['spor', 'renkli'],
      name: { tr: 'Gün batımı', en: 'Sunset' },
      cat: { tr: 'Fitness · turuncu · dönüşümlü eğim', en: 'Fitness · orange · alternating tilt' },
      template: {
        font: 'avenir', frame: 'android', deviceColor: 'black', layout: 'right',
        background: { type: 'linear', c1: '#f97316', c2: '#ef4444', angle: 145, pattern: 'diagonal', patternColor: '#ffffff', patternOpacity: 7, noise: 6, vignette: 18 },
        titleSize: 6.2, subSize: 3.1, weight: 800, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 85, textY: 8,
        deviceSize: 60, deviceY: 34, fit: 'top',
      },
      slides: [
        S(['Antrenmanını\nkaydet', 'Her set, her tekrar yerinde'], ['Log every\nworkout', 'Every set, every rep, kept']),
        S(['Programını kur', 'Haftanı önceden planla'], ['Plan your split', 'Set the week in advance'], { layout: 'left' }),
        S(['Ağırlığını artır', 'Bir sonraki hedefi uygulama söyler'], ['Add the weight', 'The app tells you the next target']),
        S(['Molanı ölç', 'Zamanlayıcı sette kendini başlatır'], ['Time your rest', 'The timer starts itself'], { layout: 'left' }),
        S(['Formunu gör', 'Hacim ve güç eğrisi tek grafikte'], ['See your shape', 'Volume and strength in one chart']),
        S(['İlk antrenman bugün', 'Ücretsiz başla'], ['First session today', 'Start for free'], { layout: 'small' }),
      ],
    },
    {
      key: 'duo',
      tags: ['foto', 'koyu'],
      name: { tr: 'İkili', en: 'Duo' },
      cat: { tr: 'Fotoğraf · iki telefon · buz mesh', en: 'Photo · two phones · ice mesh' },
      template: {
        font: 'system', frame: 'iphone-pro', deviceColor: 'white', layout: 'text-top',
        background: { type: 'mesh', c1: '#38bdf8', c2: '#a78bfa', c3: '#0b1220', pattern: 'none', noise: 8, vignette: 24 },
        titleSize: 6.0, subSize: 3.0, weight: 700, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 82, textY: 6,
        deviceSize: 52, deviceX: -14, deviceY: 36, deviceRot: -6, fit: 'top',
        device2: { on: true, frame: 'iphone-pro', color: 'graphite', w: 52, x: 18, y: 30, rot: 7, front: true, fit: 'top', shadow: 50 },
      },
      slides: [
        S(['Öncesi ve sonrası', 'Tek dokunuşta fark ortaya çıksın'], ['Before and after', 'One tap and the difference shows']),
        S(['Filmi geri getir', 'Analog tonlar, dijital kolaylık'], ['Bring the film back', 'Analogue tones, digital ease']),
        S(['Renkleri sen kur', 'Eğriler, tonlar, grenler sende'], ['Own the colour', 'Curves, tones and grain are yours']),
        S(['Ayarını sakla', 'Kendi ön ayarını bir kez kur'], ['Save the look', 'Build your preset once']),
        S(['Toplu düzenle', 'Bütün seriye aynı ton'], ['Edit in batches', 'One look across the whole set']),
        S(['Paylaşmaya hazır', 'Kalite kaybı olmadan dışa aktar'], ['Ready to post', 'Export without losing quality']),
      ],
    },
    {
      key: 'grid',
      tags: ['verimlilik', 'acik'],
      name: { tr: 'Izgara', en: 'Grid' },
      cat: { tr: 'Verimlilik · açık gri · ızgara desen', en: 'Productivity · light grey · grid' },
      template: {
        font: 'helvetica-neue', frame: 'iphone-pro', deviceColor: 'silver', layout: 'text-top',
        background: { type: 'solid', c1: '#eef0f4', pattern: 'grid', patternColor: '#0b0b0d', patternOpacity: 7, noise: 0, vignette: 10 },
        titleSize: 5.8, subSize: 2.9, weight: 700, letterSpacing: -1,
        textColor: '#111214', subColor: '#111214', subOpacity: 60, textY: 6,
        deviceSize: 62, deviceY: 30, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Bugünü topla', 'Yapılacaklar tek listede'], ['Gather your day', 'Every task in one list']),
        S(['Önceliği belirle', 'Önemli olan üstte kalsın'], ['Set the priority', 'What matters stays on top']),
        S(['Projelere böl', 'İş ve özel hayat ayrı kalsın'], ['Split into projects', 'Work and life, kept apart']),
        S(['Takvimle eşleş', 'Görevler günün içine otursun'], ['Meet your calendar', 'Tasks land inside the day']),
        S(['Tekrarı otomatikleştir', 'Her hafta yeniden yazma'], ['Automate the routine', 'Stop rewriting the same week']),
        S(['Zihnin boşalsın', 'Bugün düzeni kur'], ['Clear your head', 'Set it up today']),
      ],
    },
    {
      key: 'ocean',
      tags: ['saglik', 'renkli'],
      name: { tr: 'Okyanus', en: 'Ocean' },
      cat: { tr: 'Sağlık · metin altta · geniş harf aralığı', en: 'Wellness · text below · wide tracking' },
      template: {
        font: 'futura', frame: 'iphone-pro', deviceColor: 'silver', layout: 'text-bottom',
        background: { type: 'linear', c1: '#0ea5e9', c2: '#0f766e', angle: 165, pattern: 'none', noise: 6, vignette: 22 },
        titleSize: 5.4, subSize: 2.8, weight: 600, letterSpacing: 6,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 80, textY: 76,
        deviceSize: 58, deviceY: 6, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Nefesini yavaşlat', 'Üç dakikalık kısa seanslar'], ['Slow your breath', 'Short three-minute sessions']),
        S(['Günü sakin aç', 'Sabah ritüelin hazır'], ['Open the day calmly', 'Your morning ritual is ready']),
        S(['Uykunu izle', 'Gece boyunca ne olduğunu gör'], ['Watch your sleep', 'See what the night looked like']),
        S(['Suyunu unutma', 'Nazik hatırlatmalar'], ['Remember to drink', 'Gentle nudges, nothing loud']),
        S(['Haftanı oku', 'Ruh hâli ve enerji birlikte'], ['Read your week', 'Mood and energy side by side']),
        S(['Bugün başla', 'İlk hafta ücretsiz'], ['Begin today', 'The first week is free']),
      ],
    },
    {
      key: 'night',
      tags: ['saglik', 'koyu'],
      name: { tr: 'Gece', en: 'Night' },
      cat: { tr: 'Gece · derin siyah · sakin', en: 'Night · deep black · quiet' },
      template: {
        font: 'georgia', frame: 'iphone-pro', deviceColor: 'black', layout: 'text-top',
        background: { type: 'radial', c1: '#1e293b', c2: '#04040a', pattern: 'dots', patternColor: '#ffffff', patternOpacity: 8, noise: 10, vignette: 45 },
        titleSize: 5.6, subSize: 2.9, weight: 600, letterSpacing: 1,
        textColor: '#e2e8f0', subColor: '#94a3b8', subOpacity: 95, textY: 6,
        deviceSize: 60, deviceY: 32, deviceRot: 0, fit: 'top',
      },
      slides: [
        S(['Gece moduna geç', 'Gözünü yormayan bir arayüz'], ['Switch to night', 'An interface that spares your eyes']),
        S(['Uykuya hazırlan', 'Ekran ısınır, zihin yavaşlar'], ['Wind down', 'The screen warms, the mind slows']),
        S(['Sesleri seç', 'Yağmur, uğultu, sessizlik'], ['Choose the sound', 'Rain, hum or silence']),
        S(['Alarmın nazik olsun', 'Hafif uykuda uyandırır'], ['A kinder alarm', 'Wakes you in light sleep']),
        S(['Sabahı gör', 'Gecenin özeti kahvenle gelsin'], ['See the morning', 'Your night, summarised with coffee']),
        S(['Bu gece dene', 'Kurulum bir dakikadan kısa'], ['Try it tonight', 'Setup takes under a minute']),
      ],
    },

    /* ---------- v2: 2026 top-chart kalıpları ---------- */
    {
      key: 'indie',
      tags: ['saglik', 'verimlilik', 'acik'],
      name: { tr: 'Indie hit', en: 'Indie hit' },
      cat: { tr: 'Beyaz · dev başlık · vurgulu kelime · puan rozeti', en: 'White · huge headline · accent word · rating badge' },
      template: {
        font: 'inter', frame: 'iphone-pro', deviceColor: 'black', layout: 'hero',
        background: 'white',
        titleSize: 7.4, subSize: 3.2, weight: 800, letterSpacing: -3.5, lineHeight: 1.02,
        textColor: '#0a0a0a', subColor: '#0a0a0a', subOpacity: 55, textY: 9,
        accent: '#16a34a', hlStyle: 'color',
        deviceSize: 92, deviceX: 4, deviceY: 33, deviceRot: -6, deviceShadow: 55, fit: 'top',
      },
      slides: [
        S(['Kalorini [fotoğrafla]\nsay', 'Bir fotoğraf, tam döküm — 3 saniyede'], ['Count calories\nwith a [photo]', 'One shot, full breakdown, in 3 seconds'],
          { stickers: [{ type: 'rating', text: { tr: '4.9 · 40K değerlendirme', en: '4.9 · 40K ratings' }, x: 0, y: 3.5, size: 2.4, bg: '#111214', color: '#ffffff' }] }),
        S(['Hedefine [kilitlen]', 'Günlük makrolar kendini ayarlar'], ['[Lock in] your goal', 'Daily macros set themselves'], { deviceRot: 5, deviceX: -4 }),
        S(['İlerlemeni [gör]', 'Haftalık kilo ve enerji eğrisi'], ['[See] your progress', 'Weekly weight and energy curve'], { deviceRot: -5, deviceX: 3 }),
        S(['Barkodu okut, [bitti]', 'Paketli ürünler anında tanınır'], ['Scan the barcode, [done]', 'Packaged food is recognised instantly'], { deviceRot: 4, deviceX: -4, stickers: [{ type: 'pill', emoji: '⚡', text: { tr: '0,4 sn', en: '0.4 s' }, x: 30, y: 44, size: 3, rot: -8, bg: '#16a34a', color: '#ffffff' }] }),
        S(['[Koç] cebinde', 'Bugün ne yiyeceğini söyler'], ['A [coach] in your pocket', 'Tells you what to eat today'], { deviceRot: -4, deviceX: 3 }),
        S(['Bugün [başla]', 'İlk hafta ücretsiz, hesap gerekmez'], ['[Start] today', 'First week free, no account needed'], { deviceRot: 0, deviceX: 0, deviceSize: 84 }),
      ],
    },
    {
      key: 'ledger',
      tags: ['finans', 'koyu'],
      name: { tr: 'Defter', en: 'Ledger' },
      cat: { tr: 'Fintech · tek koyu mor · özellik çipleri', en: 'Fintech · one deep violet · feature chips' },
      template: {
        font: 'manrope', frame: 'iphone-pro', deviceColor: 'graphite', layout: 'text-top',
        background: 'deep-violet',
        titleSize: 6.4, subSize: 3.1, weight: 800, letterSpacing: -2,
        textColor: '#ffffff', subColor: '#c4b5fd', subOpacity: 90, textY: 6,
        accent: '#a78bfa', hlStyle: 'color',
        deviceSize: 70, deviceY: 29, deviceRot: 0, deviceShadow: 60, fit: 'top',
      },
      slides: [
        S(['Yurt dışında\n[komisyonsuz] harca', 'Kart, anında, gerçek kurdan'], ['Spend abroad\nwith [no fees]', 'Card, instant, at the real rate'],
          { stickers: [{ type: 'pill', emoji: '🌍', text: { tr: '150+ ülke', en: '150+ countries' }, x: 26, y: 40, size: 3, rot: 8, bg: '#a78bfa', color: '#1a1033' }] }),
        S(['Her kuruşu [gör]', 'Kategoriler kendiliğinden ayrılır'], ['[See] every cent', 'Categories sort themselves'], { stickers: [{ type: 'note', text: { tr: 'Market · ₺842', en: 'Groceries · $42' }, sub: { tr: 'Bu ay %12 daha az', en: '12% less than last month' }, time: { tr: 'şimdi', en: 'now' }, x: 0, y: 87, size: 2.5, w: 72, bg: '#ffffff', iconBg: '#a78bfa', emoji: '🛒' }] }),
        S(['Birikimi [otomatiğe] al', 'Bozuk paraları toplar, sen bakmazsın'], ['Put savings on [autopilot]', 'Rounds up the change while you live'], { stickers: [{ type: 'pill', emoji: '💰', text: { tr: '+₺1.240 bu ay', en: '+$124 this month' }, x: -24, y: 44, size: 3, rot: -7, bg: '#ffffff', color: '#1a1033' }] }),
        S(['Kilitle, [aç], kapat', 'Kartı tek dokunuşla dondur'], ['Lock, [unlock], done', 'Freeze the card with one tap'], { stickers: [{ type: 'ring', x: 4, y: 58, size: 3.6, color: '#a78bfa' }] }),
        S(['Paran [sende] kalır', 'Biyometrik giriş, anlık bildirim'], ['Your money [stays yours]', 'Biometric login, instant alerts'], { stickers: [{ type: 'pill', emoji: '🔒', text: { tr: 'Face ID', en: 'Face ID' }, x: 28, y: 40, size: 3, rot: 6, bg: '#ffffff', color: '#1a1033' }] }),
        S(['[3 dakikada] hesap aç', 'Şube yok, kâğıt yok'], ['Open an account in [3 minutes]', 'No branch, no paper'], { layout: 'bleed', deviceSize: 84 }),
      ],
    },
    {
      key: 'owl',
      tags: ['egitim', 'renkli'],
      name: { tr: 'Baykuş', en: 'Owl' },
      cat: { tr: 'Eğitim · canlı düz renkler · metin altta kutuda', en: 'Learning · vivid flat colors · text in a box below' },
      template: {
        font: 'nunito', frame: 'iphone-pro', deviceColor: 'white', layout: 'text-bottom',
        background: { type: 'solid', c1: '#58cc02' },
        titleSize: 6.2, subSize: 3.1, weight: 900, letterSpacing: -1,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 92, textY: 74,
        box: 'solid', boxColor: '#3f9a00', boxOpacity: 100, boxRadius: 4,
        accent: '#ffc800', hlStyle: 'color',
        deviceSize: 62, deviceY: 3, deviceRot: 0, deviceShadow: 40, fit: 'top',
      },
      slides: [
        S(['Günde [5 dakika]', 'Küçük dersler, büyük ilerleme'], ['[5 minutes] a day', 'Tiny lessons, big progress']),
        S(['Oyun gibi öğren', 'Puan topla, seviye atla'], ['Learn like a game', 'Earn points, level up'], { background: { type: 'solid', c1: '#1cb0f6' }, boxColor: '#0e7fbf' }),
        S(['Seriyi [koru]', 'Her gün bir adım'], ['[Keep] the streak', 'One step every day'], { background: { type: 'solid', c1: '#ff9600' }, boxColor: '#c96f00', stickers: [{ type: 'pill', emoji: '🔥', text: '42', x: 30, y: 30, size: 3.6, rot: 10, bg: '#ffffff', color: '#ff9600' }] }),
        S(['Konuşarak [ilerle]', 'Telaffuzun anında puanlanır'], ['[Speak] to progress', 'Pronunciation scored instantly'], { background: { type: 'solid', c1: '#ce82ff' }, boxColor: '#9a4fd0' }),
        S(['Arkadaşlarınla [yarış]', 'Haftalık lig, gerçek insanlar'], ['[Race] your friends', 'Weekly league, real people'], { background: { type: 'solid', c1: '#ff4b4b' }, boxColor: '#c22f2f' }),
        S(['Ücretsiz başla', 'Kayıt olmadan ilk ders'], ['Start for free', 'First lesson, no sign-up'], { background: { type: 'solid', c1: '#58cc02' } }),
      ],
    },
    {
      key: 'calm',
      tags: ['saglik', 'koyu'],
      name: { tr: 'Dingin', en: 'Serene' },
      cat: { tr: 'Sağlık · panoramik gradyan · laurel', en: 'Wellness · panoramic gradient · laurel' },
      template: {
        font: 'outfit', frame: 'iphone-pro', deviceColor: 'silver', layout: 'small',
        background: { type: 'linear', c1: '#0f2a5a', c2: '#1d9a8a', angle: 100, noise: 5, vignette: 0 },
        panorama: true,
        titleSize: 5.8, subSize: 3.0, weight: 500, letterSpacing: 0,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 78, textY: 15,
        accent: '#9fe1cf', hlStyle: 'color',
        deviceSize: 56, deviceY: 36, deviceRot: 0, deviceShadow: 45, fit: 'top',
      },
      slides: [
        S(['Daha iyi uyu,\ndaha iyi hisset', 'Uyku hikâyeleri, nefes, meditasyon'], ['Sleep better,\nfeel better', 'Sleep stories, breathing, meditation'],
          { stickers: [{ type: 'laurel', sub: { tr: 'App Store', en: 'App Store' }, text: { tr: 'Yılın\nUygulaması', en: 'App of\nthe Year' }, x: 0, y: 6, size: 2.2, color: '#ffffff' }] }),
        S(['Zihnini [yavaşlat]', 'Üç dakikalık nefes molası'], ['[Slow] your mind', 'A three-minute breathing break']),
        S(['Geceye [hazırlan]', 'Sesler ve hikâyelerle uykuya dal'], ['[Wind down] for the night', 'Drift off with sounds and stories']),
        S(['Günü sakin aç', 'Sabah ritüelin hazır'], ['Open the day calmly', 'Your morning ritual is ready']),
        S(['Ruh hâlini [izle]', 'Haftalık örüntünü gör'], ['[Track] your mood', 'See the pattern of your week']),
        S(['Bugün başla', 'İlk 7 gün ücretsiz'], ['Begin today', 'First 7 days free']),
      ],
    },
    {
      key: 'neutral',
      tags: ['verimlilik', 'acik'],
      name: { tr: 'Nötr', en: 'Neutral' },
      cat: { tr: 'Verimlilik · kâğıt beyazı · sıkı tipografi', en: 'Productivity · paper white · tight type' },
      template: {
        font: 'inter', frame: 'iphone-pro', deviceColor: 'graphite', layout: 'text-top',
        background: 'paper',
        titleSize: 5.6, subSize: 3.0, weight: 600, letterSpacing: -2.5,
        textColor: '#191919', subColor: '#191919', subOpacity: 50, textY: 7,
        accent: '#191919', hlStyle: 'underline',
        deviceSize: 72, deviceY: 27, deviceRot: 0, deviceShadow: 28, glare: false, fit: 'top',
      },
      slides: [
        S(['Her şey için\ntek çalışma alanı', 'Notlar, görevler, belgeler bir arada'], ['One workspace\nfor everything', 'Notes, tasks and docs in one place']),
        S(['Yaz, sonra [düzenle]', 'Bloklar sürüklenir, sayfa şekillenir'], ['Write, then [arrange]', 'Blocks drag, the page takes shape']),
        S(['Ekibinle [aynı sayfada]', 'Yorumlar ve bahsetmeler yerinde'], ['[On the same page] as your team', 'Comments and mentions, inline']),
        S(['Bul, [anında]', 'Arama her sayfayı ve dosyayı tarar'], ['Find it, [instantly]', 'Search covers every page and file'], { stickers: [{ type: 'pill', text: { tr: '⌘K', en: '⌘K' }, x: 26, y: 40, size: 3, rot: 0, bg: '#ffffff', color: '#191919', outline: true }] }),
        S(['Çevrimdışı da çalışır', 'Bağlantı gelince eşitlenir'], ['Works offline too', 'Syncs when you are back']),
        S(['Boş sayfayla başla', 'Ya da bir şablon seç'], ['Start with a blank page', 'Or pick a template']),
      ],
    },
    {
      key: 'track',
      tags: ['spor', 'koyu'],
      name: { tr: 'Pist', en: 'Track' },
      cat: { tr: 'Spor · siyah + turuncu · dar büyük harf', en: 'Sport · black + orange · condensed caps' },
      template: {
        font: 'bebas', frame: 'iphone-pro', deviceColor: 'black', layout: 'tilt',
        background: { type: 'solid', c1: '#0a0a0a', pattern: 'diagonal', patternColor: '#ffffff', patternOpacity: 4, noise: 8 },
        titleSize: 10.5, subSize: 3.6, weight: 400, letterSpacing: 1, lineHeight: 0.92,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 60, textY: 6,
        accent: '#fc4c02', hlStyle: 'color',
        deviceSize: 66, deviceY: 30, deviceRot: -6, deviceShadow: 60, fit: 'top',
      },
      slides: [
        S(['HER KOŞUYU\n[KAYDET]', 'GPS, tempo, nabız — tek ekranda'], ['[RECORD]\nEVERY RUN', 'GPS, pace, heart rate on one screen'],
          { stickers: [{ type: 'rating', text: { tr: '4.8 · 120K', en: '4.8 · 120K' }, x: 0, y: 26, size: 2.4, bg: '#fc4c02', color: '#ffffff', starColor: '#ffffff' }] }),
        S(['[REKORUNU]\nKIR', 'Segmentlerde kendinle yarış'], ['BEAT YOUR\n[RECORD]', 'Race yourself on every segment'], { deviceRot: 6 }),
        S(['ROTANI\n[ÇİZ]', 'Popüler yollar, yeni keşifler'], ['[DRAW]\nYOUR ROUTE', 'Popular paths, new discoveries'], { deviceRot: -6 }),
        S(['HAFTANI\n[OKU]', 'Yük, dinlenme, form eğrisi'], ['[READ]\nYOUR WEEK', 'Load, rest and fitness curve'], { deviceRot: 6 }),
        S(['EKİBİNLE\n[KOŞ]', 'Kulüpler, meydan okumalar, sıralama'], ['[RUN]\nWITH YOUR CREW', 'Clubs, challenges, leaderboard'], { deviceRot: -6, stickers: [{ type: 'pill', emoji: '🏆', text: { tr: '1. sıra', en: '#1' }, x: 28, y: 46, size: 3.2, rot: 8, bg: '#fc4c02', color: '#ffffff' }] }),
        S(['BUGÜN\n[ÇIK]', 'Ücretsiz başla'], ['GET OUT\n[TODAY]', 'Start for free'], { deviceRot: 0, layout: 'bleed', deviceSize: 84 }),
      ],
    },
    {
      key: 'glass',
      tags: ['saglik', 'verimlilik', 'renkli'],
      name: { tr: 'Cam', en: 'Glass' },
      cat: { tr: 'Mesh gradyan · cam kart · bildirim', en: 'Mesh gradient · glass card · notification' },
      template: {
        font: 'plus-jakarta', frame: 'iphone-pro', deviceColor: 'silver', layout: 'text-top',
        background: 'aurora',
        titleSize: 6.0, subSize: 3.0, weight: 800, letterSpacing: -1.5,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 82, textY: 7,
        box: 'glass', boxOpacity: 100, boxRadius: 4,
        accent: '#a3e635', hlStyle: 'color',
        deviceSize: 66, deviceY: 32, deviceRot: 0, deviceShadow: 55, fit: 'top',
      },
      slides: [
        S(['Bildirim [tam vaktinde]', 'Doğru anda, tek dokunuşla'], ['Nudges [right on time]', 'The right moment, one tap'],
          { stickers: [{ type: 'note', text: { tr: 'Su vakti 💧', en: 'Water time 💧' }, sub: { tr: '2 bardak kaldı', en: '2 glasses to go' }, time: { tr: 'şimdi', en: 'now' }, x: 0, y: 88, size: 2.5, w: 74, bg: '#ffffff', iconBg: '#22d3ee' }] }),
        S(['Alışkanlığı [kur]', 'Günde bir dokunuş yeter'], ['[Build] the habit', 'One tap a day is enough']),
        S(['Seriyi [gör]', 'Takvimin yeşile döner'], ['[See] the streak', 'Your calendar turns green'], { stickers: [{ type: 'pill', emoji: '✅', text: { tr: '21 gün', en: '21 days' }, x: 27, y: 44, size: 3, rot: -7, bg: '#ffffff', color: '#0f172a' }] }),
        S(['Saatinden [işaretle]', 'Telefonu çıkarmadan tamamla'], ['[Tick] from your wrist', 'Done without taking the phone out'], { device2: { on: true, frame: 'watch', color: 'silver', w: 24, x: 24, y: 52, rot: 6, front: true, fit: 'cover', shadow: 55 } }),
        S(['Veri [sende]', 'Hesap yok, takip yok'], ['Your data, [yours]', 'No account, no tracking']),
        S(['Bugün [başla]', 'Kurulum otuz saniye'], ['[Start] today', 'Setup takes thirty seconds']),
      ],
    },
    {
      key: 'strip',
      tags: ['foto', 'renkli'],
      name: { tr: 'Şerit', en: 'Strip' },
      cat: { tr: 'Panoramik · sıcak gradyan · dönüşümlü eğik cihaz', en: 'Panoramic · warm gradient · alternating tilt' },
      template: {
        font: 'sora', frame: 'iphone-pro', deviceColor: 'black', layout: 'right',
        background: { type: 'linear', c1: '#ff2d75', c2: '#ff9a3c', angle: 90, noise: 6 },
        panorama: true,
        titleSize: 6.2, subSize: 3.1, weight: 800, letterSpacing: -2,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 85, textY: 8,
        accent: '#fff2a8', hlStyle: 'color',
        deviceSize: 64, deviceY: 34, deviceShadow: 55, fit: 'top',
      },
      slides: [
        S(['Öncesi ve\n[sonrası]', 'Tek dokunuşta fark ortaya çıksın'], ['Before and\n[after]', 'One tap and the difference shows']),
        S(['Filmi [geri] getir', 'Analog tonlar, dijital kolaylık'], ['Bring the [film] back', 'Analogue tones, digital ease'], { layout: 'left' }),
        S(['Renkleri sen [kur]', 'Eğriler, tonlar, gren'], ['[Own] the colour', 'Curves, tones and grain']),
        S(['Ayarını [sakla]', 'Ön ayarını bir kez kur'], ['[Save] the look', 'Build your preset once'], { layout: 'left' }),
        S(['Toplu [düzenle]', 'Bütün seriye aynı ton'], ['Edit in [batches]', 'One look across the whole set']),
        S(['Paylaşmaya hazır', 'Kalite kaybı olmadan dışa aktar'], ['Ready to post', 'Export without losing quality'], { layout: 'left' }),
      ],
    },
    {
      key: 'lux',
      tags: ['verimlilik', 'koyu'],
      name: { tr: 'Lüks', en: 'Luxe' },
      cat: { tr: 'Premium · siyah + altın · serif', en: 'Premium · black + gold · serif' },
      template: {
        font: 'playfair', frame: 'iphone-pro', deviceColor: 'gold', layout: 'text-top',
        background: { type: 'radial', c1: '#26221c', c2: '#0b0a08', noise: 10, vignette: 30 },
        titleSize: 6.6, subSize: 2.9, weight: 700, letterSpacing: -1, lineHeight: 1.05,
        textColor: '#f5efe0', subColor: '#f5efe0', subOpacity: 60, textY: 7,
        accent: '#d4af37', hlStyle: 'color',
        deviceSize: 62, deviceY: 30, deviceRot: 0, deviceShadow: 65, fit: 'top',
      },
      slides: [
        S(['Zamanı [iyi]\nkullananlar için', 'Takvimin, hedefin, ritmin tek yerde'], ['For those who use\ntime [well]', 'Calendar, goals and rhythm in one place'],
          { stickers: [{ type: 'pill', text: { tr: 'PREMIUM', en: 'PREMIUM' }, x: 0, y: 26, size: 2.2, rot: 0, bg: '#d4af37', color: '#0b0a08' }] }),
        S(['Gününü [tasarla]', 'Zaman blokları, sürüklenir, oturur'], ['[Design] your day', 'Time blocks that drag and settle']),
        S(['Odak [kesintisiz]', 'Bildirimler sen bitirene kadar susar'], ['Focus, [uninterrupted]', 'Notifications wait until you finish']),
        S(['Haftayı [oku]', 'Nereye gitti, nereye gitmeli'], ['[Read] the week', 'Where it went, where it should']),
        S(['Cihazlar arası', 'Telefon, tablet, masaüstü — aynı an'], ['Across devices', 'Phone, tablet, desktop, same moment'], { device2: { on: true, frame: 'tablet', color: 'gold', w: 60, x: -30, y: 40, rot: -6, front: false, fit: 'top', shadow: 50 } }),
        S(['Bugün [başla]', 'Davetiye gerekmez'], ['[Begin] today', 'No invitation needed']),
      ],
    },
    {
      key: 'paper',
      tags: ['gunluk', 'acik'],
      name: { tr: 'Kâğıt', en: 'Paper' },
      cat: { tr: 'Krem · serif · fosforlu vurgu', en: 'Cream · serif · marker highlight' },
      template: {
        font: 'instrument-serif', frame: 'iphone-pro', deviceColor: 'silver', layout: 'text-top',
        background: { type: 'solid', c1: '#faf6ef', noise: 7 },
        titleSize: 8.2, subSize: 3.2, weight: 400, letterSpacing: -1.5, lineHeight: 1.0,
        textColor: '#1f1a14', subColor: '#1f1a14', subOpacity: 60, textY: 7,
        accent: '#ffd166', hlStyle: 'marker',
        deviceSize: 64, deviceY: 31, deviceRot: 0, deviceShadow: 35, glare: false, fit: 'top',
      },
      slides: [
        S(['Günün nasıl\n[geçti?]', 'Bir sayfa yazmak yeterli'], ['How was\n[your day?]', 'One page is enough']),
        S(['Hatırlamak için [yaz]', 'Anıların tarihiyle saklanır'], ['[Write] to remember', 'Memories kept with their dates']),
        S(['Ruh hâlini [izle]', 'Haftalık örüntünü gör'], ['[Track] your mood', 'See the pattern of your week'], { stickers: [{ type: 'pill', emoji: '🌤', text: { tr: 'iyi bir gün', en: 'a good day' }, x: 27, y: 44, size: 2.9, rot: -6, bg: '#ffffff', color: '#1f1a14' }] }),
        S(['Fotoğrafını [ekle]', 'Yazıyla birlikte o an da kalsın'], ['[Add] the photograph', 'Keep the moment next to the words']),
        S(['Sadece [sana] ait', 'Şifreli, cihazında'], ['[Yours] alone', 'Encrypted, on device']),
        S(['Bu akşam [başla]', 'İlk sayfa seni bekliyor'], ['[Start] tonight', 'The first page is waiting']),
      ],
    },
    {
      key: 'lime',
      tags: ['sosyal', 'finans', 'renkli'],
      name: { tr: 'Limon', en: 'Lime' },
      cat: { tr: 'Gen-Z · limon sarısı · geniş harf · siyah çipler', en: 'Gen-Z · lime · wide type · black chips' },
      template: {
        font: 'unbounded', frame: 'iphone-pro', deviceColor: 'black', layout: 'text-top',
        background: 'lime',
        titleSize: 5.6, subSize: 2.8, weight: 800, letterSpacing: -2, lineHeight: 1.05,
        textColor: '#0a0a0a', subColor: '#0a0a0a', subOpacity: 65, textY: 6,
        accent: '#0a0a0a', hlStyle: 'underline',
        deviceSize: 68, deviceY: 29, deviceRot: 0, deviceShadow: 50, fit: 'top',
      },
      slides: [
        S(['Bölüş,\n[bitti]', 'Hesabı üçe böl, kimse hatırlatmasın'], ['Split it,\n[done]', 'Three ways, no reminders needed'],
          { stickers: [{ type: 'pill', emoji: '🍕', text: { tr: '₺140 · 3 kişi', en: '$14 · 3 people' }, x: 26, y: 42, size: 3, rot: 8, bg: '#0a0a0a', color: '#c8f542' }] }),
        S(['Grubu [kur]', 'Link at, herkes içeride'], ['[Start] the group', 'Drop a link, everyone is in']),
        S(['Kim kime [ne] borçlu', 'Tek bakışta net'], ['Who owes [what]', 'Clear at a glance']),
        S(['Öde, [kapat]', 'Uygulamadan çıkmadan gönder'], ['Pay, [close]', 'Send without leaving the app']),
        S(['Geçmiş [temiz]', 'Her harcama, her ödeme kayıtlı'], ['History, [clean]', 'Every expense, every payment, logged']),
        S(['Ücretsiz', 'Reklam yok, abonelik yok'], ['Free', 'No ads, no subscription']),
      ],
    },

    /* ---------- v3: galeri seti ---------- */
    {
      key: 'kova',
      tags: ['verimlilik', 'egitim', 'renkli'],
      name: { tr: 'Kova', en: 'Kova' },
      cat: { tr: 'Mor düz zemin · çerçevesiz kart · yumuşak', en: 'Flat violet · frameless card · soft' },
      template: {
        font: 'plus-jakarta', frame: 'none', deviceColor: 'black', layout: 'text-top',
        background: { type: 'solid', c1: '#6c5ce7' },
        titleSize: 6.4, subSize: 3.1, weight: 800, letterSpacing: -1.5,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 80, textY: 7,
        accent: '#ffd166', hlStyle: 'color',
        deviceSize: 80, deviceY: 29, deviceRot: 0, deviceShadow: 55, fit: 'top',
      },
      slides: [
        S(['Dilini [dakikalar]\niçinde öğren', 'Günde beş dakika yeter'], ['Learn a language\nin [minutes]', 'Five minutes a day is enough']),
        S(['Konuşarak ilerle', 'Telaffuzun anında puanlanır'], ['Speak to progress', 'Pronunciation scored instantly'], { deviceRot: -6, deviceSize: 84 }),
        S(['Seriyi [koru]', 'Küçük hedefler, her gün'], ['[Keep] the streak', 'Small goals, every day'], { background: { type: 'solid', c1: '#5b4bd6' } }),
        S(['Kelimeleri hatırla', 'Aralıklı tekrar, kendiliğinden'], ['Remember the words', 'Spaced repetition, automatic'], { deviceRot: 6, deviceSize: 84 }),
        S(['[40] dil', 'İstediğin an geç'], ['[40] languages', 'Switch whenever you like'], { background: { type: 'solid', c1: '#5b4bd6' } }),
        S(['Bugün başla', 'İlk ders ücretsiz'], ['Start today', 'The first lesson is free']),
      ],
    },
    {
      key: 'nysa',
      tags: ['hava', 'arac', 'koyu'],
      name: { tr: 'Nysa', en: 'Nysa' },
      cat: { tr: 'Lacivert · mavi lekeler · çift laurel', en: 'Navy · blue blobs · twin laurels' },
      template: {
        font: 'inter', frame: 'iphone-pro', deviceColor: 'black', layout: 'text-top',
        background: { type: 'solid', c1: '#0f1b3d', pattern: 'blobs', patternColor: '#2f6bff', patternOpacity: 55, noise: 4 },
        titleSize: 6.6, subSize: 3.0, weight: 800, letterSpacing: -1, lineHeight: 1.05,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 75, textY: 6,
        accent: '#8ab4ff', hlStyle: 'color',
        deviceSize: 64, deviceY: 36, deviceRot: 0, deviceShadow: 60, fit: 'top',
      },
      slides: [
        S(['SANA GÖRE\nHAVA', 'Konumuna ve gününe göre tahmin'], ['WEATHER MADE\nFOR YOU', 'Forecast for your place and your day'],
          { stickers: [
            { type: 'laurel', text: { tr: '4.6\nPuan', en: '4.6\nRating' }, x: -19, y: 27, size: 2.6 },
            { type: 'laurel', text: { tr: 'Editör\nSeçimi', en: 'Editors\nChoice' }, x: 19, y: 27, size: 2.6 },
          ], deviceY: 40 }),
        S(['GECE GÖĞÜNÜ\nKEŞFET', 'Altın saat, ay evresi, yıldızlar'], ['DISCOVER THE\nNIGHT SKY', 'Golden hour, moon and stars'], { layout: 'text-bottom', textY: 74, deviceY: 4 }),
        S(['TEK BAKIŞTA\nCANLI HAVA', 'Şu an ne oluyor, gör'], ['LIVE WEATHER\nAT A GLANCE', 'See what is happening right now']),
        S(['SAATLİK\nPLANLA', 'Yağmur ne zaman başlar, biter'], ['PLAN BY\nTHE HOUR', 'When the rain starts and stops'], { layout: 'text-bottom', textY: 74, deviceY: 4 }),
        S(['UYARILAR\nÖNDEN GELİR', 'Fırtına, don, rüzgâr bildirimi'], ['ALERTS COME\nFIRST', 'Storm, frost and wind notifications'], { stickers: [{ type: 'note', text: { tr: 'Yağmur 15 dk sonra', en: 'Rain in 15 min' }, sub: { tr: 'Şemsiyeni al', en: 'Take the umbrella' }, time: { tr: 'şimdi', en: 'now' }, x: 0, y: 87, size: 2.5, w: 74, bg: '#ffffff', iconBg: '#2f6bff', emoji: '🌧' }] }),
        S(['ÜCRETSİZ\nBAŞLA', 'Reklam yok, hesap yok'], ['START\nFOR FREE', 'No ads, no account']),
      ],
    },
    {
      key: 'vela',
      tags: ['egitim', 'verimlilik', 'koyu'],
      name: { tr: 'Vela', en: 'Vela' },
      cat: { tr: 'Koyu lacivert · büyük harf · sarı vurgu · laurel', en: 'Deep navy · caps · yellow accent · laurel' },
      template: {
        font: 'sora', frame: 'iphone-pro', deviceColor: 'black', layout: 'bleed',
        background: { type: 'radial', c1: '#1f2b6b', c2: '#0a1030', noise: 6, vignette: 20 },
        titleSize: 6.6, subSize: 3.0, weight: 800, letterSpacing: -1, lineHeight: 1.05,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 75, textY: 6,
        accent: '#facc15', hlStyle: 'color',
        deviceSize: 82, deviceY: 30, deviceRot: 0, deviceShadow: 60, fit: 'top',
      },
      slides: [
        S(['DAHA [KESKİN]\nBİR ZİHİN', 'Günde 15 dakikalık özetler'], ['A [SHARPER]\nMIND', '15-minute summaries a day'],
          { stickers: [{ type: 'laurel', text: { tr: '1M+ MUTLU\nKULLANICI', en: '1M+ HAPPY\nCUSTOMERS' }, x: 0, y: 90, size: 2.4 }] }),
        S(['KARMAŞIK FİKİR\n[NET] ANLATIM', 'Şemalar ve görsellerle'], ['COMPLEX IDEAS\nMADE [CLEAR]', 'With diagrams and visuals'], { stickers: [{ type: 'pill', text: { tr: '2 DAKİKA', en: '2 MINUTES' }, x: 0, y: 91, size: 2.6, bg: '#facc15', color: '#0a1030' }] }),
        S(['GEL, [BÜYÜDÜĞÜNÜ]\nİZLE', 'Seri ve ilerleme tek ekranda'], ['SHOW UP AND\nWATCH IT [COMPOUND]', 'Streak and progress on one screen']),
        S(['İLK ÖZETİNİ\n[BUGÜN] OKU', 'Kütüphane seni bekliyor'], ['READ YOUR FIRST\nSUMMARY [TODAY]', 'The library is waiting']),
        S(['DİNLE YA DA\n[OKU]', 'Yolda sesli, evde yazılı'], ['LISTEN OR\n[READ]', 'Audio on the go, text at home']),
        S(['ÜCRETSİZ\nBAŞLA', '7 gün, kart yok'], ['START\n[FREE]', '7 days, no card']),
      ],
    },
    {
      key: 'innerglow',
      tags: ['saglik', 'spor', 'koyu'],
      name: { tr: 'İç ışık', en: 'Inner glow' },
      cat: { tr: 'Siyah · cihaz arkasında renkli ışıma', en: 'Black · coloured glow behind the device' },
      template: {
        font: 'inter', frame: 'iphone-pro', deviceColor: 'black', layout: 'text-top',
        background: { type: 'solid', c1: '#050505', noise: 6 },
        titleSize: 6.6, subSize: 3.0, weight: 700, letterSpacing: -2.5, lineHeight: 1.05,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 65, textY: 7,
        accent: '#4ade80', hlStyle: 'color',
        deviceSize: 70, deviceY: 26, deviceRot: 0, deviceShadow: 0, glow: '#ef4444', glowStrength: 60, fit: 'top',
      },
      slides: [
        S(['Nabzını\n[takip et]', 'Gün boyu, otomatik'], ['Keep track\nof your [heart]', 'All day, automatically'], { glow: '#ef4444' }),
        S(['Uykunu\n[oku]', 'Evreler ve kalite skoru'], ['Read your\n[sleep]', 'Stages and a quality score'], { glow: '#3b82f6' }),
        S(['Adımlarını\n[say]', 'Hedef, seri, rozet'], ['Count your\n[steps]', 'Goal, streak, badges'], { glow: '#4ade80' }),
        S(['Antrenmanı\n[kaydet]', 'Koşu, bisiklet, yüzme'], ['Log the\n[workout]', 'Run, ride, swim'], { glow: '#f59e0b' }),
        S(['Haftanı\n[karşılaştır]', 'Geçen haftaya göre nerede olduğun'], ['[Compare]\nyour week', 'Where you stand vs last week'], { glow: '#a855f7' }),
        S(['Saatinle\n[eşle]', 'Veri anında telefonda'], ['[Pair] with\nyour watch', 'Data lands on the phone instantly'], { glow: '#22d3ee', device2: { on: true, frame: 'watch', color: 'black', w: 24, x: 24, y: 50, rot: 8, front: true, fit: 'cover', shadow: 50 } }),
      ],
    },
    {
      key: 'photoedit',
      tags: ['foto', 'koyu'],
      name: { tr: 'Fotoğraf', en: 'Photo edit' },
      cat: { tr: 'Çerçevesiz tam ekran · serif başlık · fotoğrafın kendisi zemin', en: 'Frameless full-bleed · serif headline · the photo is the background' },
      template: {
        font: 'playfair', frame: 'none', deviceColor: 'black', layout: 'full',
        background: 'black',
        titleSize: 6.8, subSize: 3.0, weight: 700, letterSpacing: 0, lineHeight: 1.05,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 80, textY: 5, shadow: true,
        accent: '#ffffff', hlStyle: 'underline',
        deviceSize: 100, deviceY: 0, deviceRot: 0, deviceShadow: 0, fit: 'cover',
      },
      slides: [
        S(['KAMERAN\n[SİNEMATİK]', 'Tek dokunuşta film tonu'], ['YOUR CAMERA\nBUT [CINEMATIC]', 'Film tone in one tap']),
        S(['FİLM DOKUSU\nTEK DOKUNUŞTA', 'Gren, kontrast, renk'], ['FILM LOOK\nON ONE TAP', 'Grain, contrast, colour']),
        S(['[PRO] GİBİ\nÇEK', 'Manuel pozlama ve odak'], ['CAPTURE\nLIKE A [PRO]', 'Manual exposure and focus']),
        S(['RENKLERİ\n[YÖNET]', 'Eğriler, HSL, ayrık ton'], ['[GRADE]\nTHE COLOUR', 'Curves, HSL, split tone']),
        S(['ÖN AYARINI\nSAKLA', 'Bütün seriye aynı ton'], ['SAVE YOUR\nPRESET', 'One look across the whole set']),
        S(['KAYIPSIZ\nDIŞA AKTAR', 'RAW ve ProRes desteği'], ['EXPORT\nLOSSLESS', 'RAW and ProRes support']),
      ],
    },
    {
      key: 'blast',
      tags: ['oyun', 'renkli'],
      name: { tr: 'Patlat', en: 'Blast' },
      cat: { tr: 'Oyun · turuncu-pembe · çerçevesiz tam · alt kutu', en: 'Game · orange-pink · frameless full · bottom box' },
      template: {
        font: 'nunito', frame: 'none', deviceColor: 'black', layout: 'full',
        background: { type: 'linear', c1: '#ff7a18', c2: '#ff2d95', angle: 160 },
        titleSize: 7.2, subSize: 3.1, weight: 900, letterSpacing: -1, lineHeight: 1.0,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 90, textY: 76,
        box: 'solid', boxColor: '#1a0b2e', boxOpacity: 85, boxRadius: 5,
        accent: '#ffe066', hlStyle: 'color',
        deviceSize: 100, deviceY: 0, deviceRot: 0, deviceShadow: 0, fit: 'cover',
      },
      slides: [
        S(['[PATLAT]\nVE GEÇ', 'Binlerce bölüm seni bekliyor'], ['[BLAST]\nTHROUGH', 'Thousands of levels are waiting'],
          { stickers: [{ type: 'pill', emoji: '⭐', text: { tr: 'YENİ', en: 'NEW' }, x: 30, y: 6, size: 3.2, rot: 8, bg: '#ffe066', color: '#1a0b2e' }] }),
        S(['GÜÇLERİ\n[BİRLEŞTİR]', 'Roket + bomba = tahta temiz'], ['[COMBINE]\nPOWER-UPS', 'Rocket + bomb = clean board']),
        S(['HER GÜN\n[HEDİYE]', 'Giriş yap, ödülünü al'], ['A [GIFT]\nEVERY DAY', 'Log in, collect the reward']),
        S(['ARKADAŞLARINLA\n[YARIŞ]', 'Haftalık lig tabloları'], ['[RACE]\nYOUR FRIENDS', 'Weekly leaderboards']),
        S(['ÇEVRİMDIŞI\nOYNA', 'İnternet gerekmez'], ['PLAY\nOFFLINE', 'No internet needed']),
        S(['ŞİMDİ\n[İNDİR]', 'Ücretsiz'], ['[DOWNLOAD]\nNOW', 'Free to play']),
      ],
    },
    {
      key: 'bank',
      tags: ['finans', 'koyu'],
      name: { tr: 'Banka', en: 'Bank' },
      cat: { tr: 'Siyah · limon vurgu · dönüşümlü eğik · laurel', en: 'Black · lime accent · alternating tilt · laurel' },
      template: {
        font: 'manrope', frame: 'iphone-pro', deviceColor: 'graphite', layout: 'right',
        background: { type: 'solid', c1: '#000000', noise: 5 },
        titleSize: 6.4, subSize: 3.0, weight: 800, letterSpacing: -2, lineHeight: 1.05,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 65, textY: 8,
        accent: '#c8f542', hlStyle: 'color',
        deviceSize: 64, deviceY: 32, deviceShadow: 60, fit: 'top',
      },
      slides: [
        S(['Maaşın\n[2 gün] erken', 'Doğrudan yatırma ile'], ['Get paid\n[2 days] early', 'With direct deposit'],
          { stickers: [{ type: 'laurel', text: { tr: '250K\nKullanıcı', en: '250K\nUsers' }, x: -28, y: 78, size: 2.4 }] }),
        S(['Ücret [yok]', 'Aylık ücret yok, minimum yok'], ['[No] fees', 'No monthly fee, no minimum'], { layout: 'left' }),
        S(['Harcadıkça\n[kazan]', 'Her alışverişte puan'], ['[Earn] as\nyou spend', 'Points on every purchase'], { stickers: [{ type: 'pill', emoji: '💸', text: { tr: '+₺35 iade', en: '+$3.50 back' }, x: -26, y: 44, size: 3, rot: -6, bg: '#c8f542', color: '#000000' }] }),
        S(['Kartı [dondur]', 'Tek dokunuş, anında'], ['[Freeze] the card', 'One tap, instantly'], { layout: 'left' }),
        S(['Birikim [hedefleri]', 'Kovalara böl, otomatik doldur'], ['Savings [pods]', 'Split into pods, fill automatically']),
        S(['[3 dakikada] aç', 'Kimlik ve selfie yeter'], ['Open in [3 minutes]', 'ID and a selfie are enough'], { layout: 'bleed', deviceSize: 84 }),
      ],
    },
    {
      key: 'pastel',
      tags: ['yasam', 'gunluk', 'acik', 'renkli'],
      name: { tr: 'Pastel', en: 'Pastel' },
      cat: { tr: 'Pembe-nane-lavanta dönüşümlü · yuvarlak font', en: 'Pink-mint-lavender alternating · rounded type' },
      template: {
        font: 'nunito', frame: 'iphone-pro', deviceColor: 'white', layout: 'text-top',
        background: { type: 'solid', c1: '#ffd6e7' },
        titleSize: 6.4, subSize: 3.1, weight: 900, letterSpacing: -1,
        textColor: '#3b2a3a', subColor: '#3b2a3a', subOpacity: 65, textY: 7,
        accent: '#ff5c8a', hlStyle: 'marker', hlTextColor: '#ffffff',
        deviceSize: 66, deviceY: 29, deviceRot: 0, deviceShadow: 35, fit: 'top',
      },
      slides: [
        S(['Kendine [iyi] bak', 'Küçük alışkanlıklar, yumuşak hatırlatmalar'], ['Be [kind] to yourself', 'Small habits, gentle reminders']),
        S(['Suyunu [iç]', 'Bardak bardak takip'], ['[Drink] your water', 'Glass by glass'], { background: { type: 'solid', c1: '#d6f5ea' }, accent: '#1fb98a' }),
        S(['Ruh hâlini [yaz]', 'Bir emoji yeter'], ['[Log] your mood', 'One emoji is enough'], { background: { type: 'solid', c1: '#e6ddff' }, accent: '#7c5cff' }),
        S(['Adetini [takip et]', 'Tahmin ve bildirim'], ['[Track] your cycle', 'Prediction and reminders'], { background: { type: 'solid', c1: '#ffd6e7' } }),
        S(['Uykunu [koru]', 'Yatma saati ritüeli'], ['[Protect] your sleep', 'A bedtime ritual'], { background: { type: 'solid', c1: '#d6f5ea' }, accent: '#1fb98a' }),
        S(['Bugün [başla]', 'Ücretsiz, reklamsız'], ['[Start] today', 'Free, no ads'], { background: { type: 'solid', c1: '#e6ddff' }, accent: '#7c5cff' }),
      ],
    },
    {
      key: 'terminal',
      tags: ['arac', 'verimlilik', 'koyu'],
      name: { tr: 'Terminal', en: 'Terminal' },
      cat: { tr: 'Geliştirici · koyu ızgara · mono · yeşil', en: 'Developer · dark grid · mono · green' },
      template: {
        font: 'space-grotesk', frame: 'iphone-pro', deviceColor: 'black', layout: 'text-top',
        background: { type: 'solid', c1: '#0d1117', pattern: 'grid', patternColor: '#58a6ff', patternOpacity: 10 },
        titleSize: 6.0, subSize: 3.0, weight: 700, letterSpacing: -1.5,
        textColor: '#e6edf3', subColor: '#8b949e', subOpacity: 100, textY: 7,
        accent: '#3fb950', hlStyle: 'color',
        deviceSize: 68, deviceY: 28, deviceRot: 0, deviceShadow: 50, glare: false, fit: 'top',
      },
      slides: [
        S(['Sunucunu\n[cepten] izle', 'CPU, bellek, uptime — canlı'], ['Watch your server\nfrom your [pocket]', 'CPU, memory, uptime, live'],
          { stickers: [{ type: 'pill', text: { tr: '● çevrimiçi', en: '● online' }, x: 27, y: 42, size: 2.8, bg: '#0d1117', color: '#3fb950', outline: true }] }),
        S(['Loglar [akarken]', 'Filtrele, ara, işaretle'], ['Logs as they [stream]', 'Filter, search, flag']),
        S(['Uyarı [önce] gelsin', 'Eşik aşılınca bildirim'], ['Alerts [first]', 'Notified when a threshold is crossed'], { stickers: [{ type: 'note', text: { tr: 'CPU %92', en: 'CPU 92%' }, sub: { tr: 'api-01 · 2 dk', en: 'api-01 · 2 min' }, time: { tr: 'şimdi', en: 'now' }, x: 0, y: 87, size: 2.5, w: 74, bg: '#161b22', color: '#e6edf3', iconBg: '#f85149', emoji: '!' }] }),
        S(['SSH [tek] dokunuş', 'Anahtarların cihazında kalır'], ['SSH in [one] tap', 'Keys stay on the device']),
        S(['Ekibinle [paylaş]', 'Panolar ve erişim rolleri'], ['[Share] with the team', 'Dashboards and access roles']),
        S(['Açık kaynak', 'Kod GitHub\'da'], ['Open source', 'The code is on GitHub']),
      ],
    },
    {
      key: 'sky',
      tags: ['hava', 'seyahat', 'acik'],
      name: { tr: 'Gök', en: 'Sky' },
      cat: { tr: 'Açık mavi gradyan · beyaz daireler · hafif', en: 'Light blue gradient · white circles · airy' },
      template: {
        font: 'outfit', frame: 'iphone-pro', deviceColor: 'silver', layout: 'text-top',
        background: { type: 'linear', c1: '#bfe3ff', c2: '#eaf6ff', angle: 180, pattern: 'circles', patternColor: '#ffffff', patternOpacity: 45 },
        titleSize: 6.4, subSize: 3.0, weight: 700, letterSpacing: -1.5,
        textColor: '#0b2a4a', subColor: '#0b2a4a', subOpacity: 60, textY: 7,
        accent: '#0a84ff', hlStyle: 'color',
        deviceSize: 66, deviceY: 29, deviceRot: 0, deviceShadow: 30, fit: 'top',
      },
      slides: [
        S(['Bugün [ne] giysem?', 'Havaya göre kombin önerisi'], ['[What] to wear today?', 'Outfit suggestion from the forecast']),
        S(['Saatlik [yağış]', 'Dakikası dakikasına'], ['[Rain] by the hour', 'Down to the minute']),
        S(['10 günlük [plan]', 'Hafta sonunu önceden gör'], ['A 10-day [plan]', 'See the weekend in advance']),
        S(['Widget\'ta [hep] açık', 'Kilit ekranında bile'], ['[Always] on the widget', 'Even on the lock screen']),
        S(['Seyahatte [yanında]', 'Gideceğin şehri ekle'], ['[With] you on trips', 'Add the city you are going to']),
        S(['Ücretsiz [başla]', 'Reklamsız ilk ay'], ['[Start] free', 'Ad-free first month']),
      ],
    },
    {
      key: 'travel',
      tags: ['seyahat', 'yasam', 'renkli'],
      name: { tr: 'Yolculuk', en: 'Journey' },
      cat: { tr: 'Turkuaz-turuncu · çapraz şerit · eğik', en: 'Teal-orange · diagonal stripe · tilted' },
      template: {
        font: 'bricolage', frame: 'iphone-pro', deviceColor: 'white', layout: 'tilt',
        background: { type: 'linear', c1: '#0f766e', c2: '#134e4a', angle: 160, pattern: 'stripe', patternColor: '#f97316', patternOpacity: 90 },
        titleSize: 6.6, subSize: 3.0, weight: 800, letterSpacing: -1.5, lineHeight: 1.05,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 80, textY: 6,
        accent: '#fdba74', hlStyle: 'color',
        deviceSize: 64, deviceY: 30, deviceRot: -7, deviceShadow: 60, fit: 'top',
      },
      slides: [
        S(['Rotanı [çiz]', 'Şehirler, günler, duraklar'], ['[Draw] your route', 'Cities, days, stops'], { stickers: [{ type: 'pill', emoji: '✈️', text: { tr: '12 gün · 4 şehir', en: '12 days · 4 cities' }, x: 26, y: 44, size: 3, rot: 6, bg: '#ffffff', color: '#134e4a' }] }),
        S(['Uçuşu [takip et]', 'Kapı, gecikme, bagaj bandı'], ['[Track] the flight', 'Gate, delay, carousel'], { deviceRot: 7 }),
        S(['Çevrimdışı [harita]', 'İnternet olmadan yön bul'], ['Offline [maps]', 'Find your way without signal'], { deviceRot: -7 }),
        S(['Bütçeyi [tut]', 'Döviz otomatik çevrilir'], ['[Keep] the budget', 'Currency converts itself'], { deviceRot: 7 }),
        S(['Anıları [sakla]', 'Fotoğraf ve notlar güne bağlı'], ['[Keep] the memories', 'Photos and notes pinned to the day'], { deviceRot: -7 }),
        S(['Yola [çık]', 'Ücretsiz plan'], ['[Go]', 'Free plan'], { deviceRot: 0, layout: 'bleed', deviceSize: 84 }),
      ],
    },
    {
      key: 'food',
      tags: ['yemek', 'yasam', 'acik'],
      name: { tr: 'Mutfak', en: 'Kitchen' },
      cat: { tr: 'Krem · turuncu · yuvarlak · emoji çipler', en: 'Cream · orange · rounded · emoji chips' },
      template: {
        font: 'nunito', frame: 'iphone-pro', deviceColor: 'white', layout: 'text-top',
        background: { type: 'solid', c1: '#fff4e6', pattern: 'dots', patternColor: '#f97316', patternOpacity: 12 },
        titleSize: 6.6, subSize: 3.1, weight: 900, letterSpacing: -1,
        textColor: '#2a1a0a', subColor: '#2a1a0a', subOpacity: 60, textY: 7,
        accent: '#f97316', hlStyle: 'color',
        deviceSize: 66, deviceY: 29, deviceRot: 0, deviceShadow: 35, fit: 'top',
      },
      slides: [
        S(['Bu akşam [ne] var?', 'Dolabındakilerden tarif'], ['[What]\'s for dinner?', 'Recipes from what is in the fridge'], { stickers: [{ type: 'pill', emoji: '🍝', text: { tr: '20 dk', en: '20 min' }, x: 28, y: 44, size: 3.2, rot: -6, bg: '#ffffff', color: '#2a1a0a' }] }),
        S(['Listeyi [kendisi] yazar', 'Tarifi seç, market listesi hazır'], ['The list [writes] itself', 'Pick the recipe, the shopping list is ready']),
        S(['Adım [adım]', 'Ellerin hamurdayken sesle ilerle'], ['Step by [step]', 'Go by voice while your hands are busy']),
        S(['Haftayı [planla]', 'Yedi gün, tek tabla'], ['[Plan] the week', 'Seven days, one board'], { stickers: [{ type: 'pill', emoji: '🥗', text: { tr: 'Salı · hafif', en: 'Tue · light' }, x: -26, y: 42, size: 3, rot: 6, bg: '#ffffff', color: '#2a1a0a' }] }),
        S(['Kalori [görünür]', 'Porsiyon başına döküm'], ['Calories [visible]', 'Per-portion breakdown']),
        S(['Bugün [pişir]', 'İlk 100 tarif ücretsiz'], ['[Cook] today', 'First 100 recipes free']),
      ],
    },
    {
      key: 'news',
      tags: ['haber', 'gunluk', 'acik'],
      name: { tr: 'Gazete', en: 'Gazette' },
      cat: { tr: 'Beyaz · serif manşet · kırmızı alt çizgi', en: 'White · serif headline · red underline' },
      template: {
        font: 'dm-serif', frame: 'iphone-pro', deviceColor: 'black', layout: 'small',
        background: { type: 'solid', c1: '#ffffff' },
        titleSize: 7.6, subSize: 3.0, weight: 400, letterSpacing: -1.5, lineHeight: 1.0,
        textColor: '#111111', subColor: '#111111', subOpacity: 55, textY: 7,
        accent: '#d90429', hlStyle: 'underline',
        deviceSize: 58, deviceY: 34, deviceRot: 0, deviceShadow: 40, fit: 'top',
      },
      slides: [
        S(['Sabah [5] dakika', 'Günün özeti, reklamsız'], ['[5] minutes\nevery morning', 'The day in brief, no ads']),
        S(['Kaynağı [gör]', 'Her haberde orijinal link'], ['[See] the source', 'The original link on every story']),
        S(['Konuları [seç]', 'Sadece ilgilendiğin'], ['[Pick] your topics', 'Only what you care about']),
        S(['Sesli [dinle]', 'Yolda, kulaklıkla'], ['[Listen] aloud', 'On the road, with headphones']),
        S(['Sonra [oku]', 'Çevrimdışı kaydet'], ['Read [later]', 'Save offline']),
        S(['Abone [ol]', 'İlk ay ücretsiz'], ['[Subscribe]', 'First month free']),
      ],
    },
    {
      key: 'kids',
      tags: ['egitim', 'cocuk', 'oyun', 'renkli'],
      name: { tr: 'Çocuk', en: 'Kids' },
      cat: { tr: 'Sarı · turuncu lekeler · kalın yuvarlak', en: 'Yellow · orange blobs · chunky rounded' },
      template: {
        font: 'nunito', frame: 'iphone-pro', deviceColor: 'white', layout: 'text-top',
        background: { type: 'solid', c1: '#ffd60a', pattern: 'blobs', patternColor: '#ff9500', patternOpacity: 70 },
        titleSize: 7.0, subSize: 3.2, weight: 900, letterSpacing: -1.5, lineHeight: 1.0,
        textColor: '#1d1d1f', subColor: '#1d1d1f', subOpacity: 70, textY: 7,
        accent: '#ffffff', hlStyle: 'marker', hlTextColor: '#1d1d1f',
        deviceSize: 66, deviceY: 30, deviceRot: -4, deviceShadow: 40, fit: 'top',
      },
      slides: [
        S(['Oyunla [öğren]', 'Harfler, sayılar, renkler'], ['[Learn] by playing', 'Letters, numbers, colours'], { stickers: [{ type: 'pill', emoji: '🎈', text: { tr: '3-6 yaş', en: 'Ages 3-6' }, x: 27, y: 44, size: 3.2, rot: 8, bg: '#ffffff', color: '#1d1d1f' }] }),
        S(['Reklam [yok]', 'Satın alma yok, güvenli'], ['[No] ads', 'No purchases, safe'], { deviceRot: 4 }),
        S(['Kendi [hızında]', 'Zorluk kendini ayarlar'], ['At their own [pace]', 'Difficulty adjusts itself'], { deviceRot: -4 }),
        S(['Ebeveyn [paneli]', 'Ne öğrendi, gör'], ['Parent [panel]', 'See what they learned'], { deviceRot: 4 }),
        S(['Çevrimdışı [oyna]', 'Arabada, uçakta'], ['Play [offline]', 'In the car, on the plane'], { deviceRot: -4 }),
        S(['Bugün [başla]', 'İlk 10 oyun ücretsiz'], ['[Start] today', 'First 10 games free'], { deviceRot: 0 }),
      ],
    },
    {
      key: 'split',
      tags: ['verimlilik', 'sosyal', 'renkli'],
      name: { tr: 'Çift kare', en: 'Split frames' },
      cat: { tr: 'Panorama · cihaz iki kareye yayılır · 3 çift', en: 'Panorama · device spans two frames · 3 pairs' },
      template: {
        font: 'outfit', frame: 'iphone-pro', deviceColor: 'black', layout: 'span-left',
        background: { type: 'linear', c1: '#4f46e5', c2: '#06b6d4', angle: 90, noise: 5 },
        panorama: true,
        titleSize: 6.4, subSize: 3.0, weight: 800, letterSpacing: -2,
        textColor: '#ffffff', subColor: '#ffffff', subOpacity: 82, textY: 7,
        accent: '#fde68a', hlStyle: 'color',
        deviceSize: 96, deviceY: 26, deviceShadow: 60, fit: 'top',
      },
      slides: [
        S(['Her şey\n[tek] yerde', 'Görevler, notlar, takvim'], ['Everything in\n[one] place', 'Tasks, notes, calendar'], { layout: 'span-left' }),
        S(['Ekibinle\n[aynı] sayfada', 'Canlı düzenleme'], ['[Same] page\nas your team', 'Live editing'], { layout: 'span-right' }),
        S(['Bugünü\n[planla]', 'Öncelik otomatik'], ['[Plan]\ntoday', 'Priority sorts itself'], { layout: 'span-left' }),
        S(['Yarını\n[gör]', 'Takvim ve görev iç içe'], ['[See]\ntomorrow', 'Calendar and tasks together'], { layout: 'span-right' }),
        S(['Cebinden\n[bitir]', 'Widget ve kısayollar'], ['[Finish] from\nyour pocket', 'Widgets and shortcuts'], { layout: 'span-left' }),
        S(['Bugün\n[başla]', 'Ücretsiz plan'], ['[Start]\ntoday', 'Free plan'], { layout: 'span-right' }),
      ],
    },
  ];
})(window);
